#! /bin/sh



pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d IV V VI
bspc monitor DP-4 -d I II III
bspc monitor HDMI-0 -d VII VIII IX


bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true



# Border
bspc config focused_border_color        "#689D6A"
bspc config normal_border_color         "#504945"
bspc config active_border_color         "#689d6a"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Picom
# picom -b &
picom
# Dex
# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

