#! /bin/sh



pkill -x sxhkd; sxhkd &
pkill polybar &


bspc monitor DP-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII 

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true



# Border
bspc config focused_border_color        "#689D6A"
bspc config normal_border_color         "#504945"
bspc config active_border_color         "#689d6a"

#
# Autostart
#
# Set display from arandr saved script
xrandr --output DP-1 --mode 2560x1440 --refresh 143.91
xrandr --output eDP-1 --mode 2560x1600
# Bar
polybar top1 &
polybar top2 &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Picom
picom &
# Cursor
xsetroot -cursor_name left_ptr &

setxkbmap us & 

xbacklight -dec 20

#Window Rules




