cursor #ddc7a1
cursor_text_color #d4be98

foreground            #ddc7a1
background            #1d2021
selection_foreground  #141617
selection_background  #e78a4e
url_color             #a9b665

color0   #141617
color1   #d16e5e
color2   #64b65b
color3   #e3d166
color4   #9eac50
color5   #49540f
color6   #a9b665
color7   #bdbfb3
color8   #7a7c73
color9   #f5a699
color10  #95da8d
color11  #fff1a5
color12  #bcc87c
color13  #e0eca2
color14  #f6fecb
color15  #fdfff8
