github.com:
    users:
        noahbaldinger:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: noahbaldinger
